"""
Django settings for sargia_backend project.

Generated by 'django-admin startproject' using Django 6.0.7.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d%9x^&+82rgz^a1m8ua=h2#0tv^%t#*p3@-me(ue%w)8eh(nq9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sargia_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sargia_backend.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files
STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS
CORS_ALLOW_ALL_ORIGINS = True

# ─────────────────────────────────────────────────
# Google Sheets Integration
# ─────────────────────────────────────────────────
# SETUP GUIDE:
# 1. Go to https://console.cloud.google.com/
# 2. Create a project, enable Google Sheets API and Google Drive API.
# 3. Create a Service Account and download the JSON key as "credentials.json".
# 4. Place credentials.json in /backend/ directory (same level as manage.py).
# 5. Share your Google Sheet with the Service Account email as an Editor.
# 6. Copy the Spreadsheet ID from the URL and set GOOGLE_SHEET_ID below,
#    or export it as an environment variable: set GOOGLE_SHEET_ID=your_id_here
# ─────────────────────────────────────────────────

GOOGLE_SHEETS_CREDENTIALS_FILE = os.path.join(BASE_DIR, 'google_credentials.json')
GOOGLE_SHEET_ID = os.environ.get('GOOGLE_SHEET_ID', '1A3L0BMAks3s99WhbKjfnZwenydE7aeKiyHK7zSZa5YU')
